server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: /
  forward-headers-strategy: NATIVE
  error:
    whitelabel:
      enabled: false

spring:
  security:
    user:
      name: admin
      password: admin
      roles: USER
  jmx:
    enabled: true
    default_domain: DbLoadgen
  jackson:
    deserialization:
      fail_on_unknown_properties: false
      read_unknown_enum_values_as_null: true


management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: "*"
  server:
    port: 9090

dbloadgen:
  directory: ./datasets
